title = 'Wildlife & Astronomy Collection'
languageCode = 'en-us'
copyright = "© Yixiu Liu"
defaultContentLanguage = "en"
timezone = "America/Los_Angeles"
theme = ["github.com/nicokaiser/hugo-theme-gallery/v2"]

[params]
  title = "Yixiu's Wildlife and Astronomy Collection"
  defaultTheme = "dark"

[author]
  name = "Yixiu Liu"